"""Exact small logical Pauli Lie closure and local pure-state Fisher diagnostics."""

import numpy as np


def pauli_lie_dimension(generators):
    """Dimension of the real Lie algebra generated by iP for Pauli strings.

    Commuting strings give zero; anticommuting strings yield their product
    up to a nonzero scalar. This exact binary closure avoids rank tolerances.
    It describes arbitrary-depth products, not finite-depth expressivity.
    """
    generators = tuple(generators)
    if not generators:
        return 0
    n = len(generators[0])
    if not 1 <= n <= 6 or any(len(g) != n or set(g) - set("IXYZ") for g in generators):
        raise ValueError("Use equal-length Pauli strings on 1 to 6 logical qubits")
    codes = {"I": (0, 0), "X": (1, 0), "Y": (1, 1), "Z": (0, 1)}
    known = set()
    for generator in generators:
        x = sum(codes[p][0] << k for k, p in enumerate(generator))
        z = sum(codes[p][1] << k for k, p in enumerate(generator))
        known.add((x, z))
    basis = list(known)
    i = 0
    while i < len(basis):
        x, z = basis[i]
        for y, w in basis[:i]:
            if ((x & w).bit_count() + (z & y).bit_count()) % 2:
                product = (x ^ y, z ^ w)
                if product not in known:
                    known.add(product)
                    basis.append(product)
        i += 1
    return len(basis)


def state_fisher(model, input_state, parameters, step=1e-5):
    """Local pure-state QFI matrix using central state derivatives.

    Parameters must be the active vector. Rank is a local numerical diagnostic;
    it is not the statistical effective dimension or a layer inclusion proof.
    """
    values = np.asarray(parameters, dtype=float)
    if values.shape != (model.n_parameters,) or not np.isfinite(step) or step <= 0:
        raise ValueError("Use the active parameter vector and a positive finite step")
    psi = model.run(input_state, values).state
    derivatives = []
    for delta in np.eye(len(values)) * step:
        derivatives.append(
            (
                model.run(input_state, values + delta).state
                - model.run(input_state, values - delta).state
            )
            / (2 * step)
        )
    jac = np.asarray(derivatives, dtype=complex).reshape(len(values), len(psi))
    overlaps = jac.conj() @ psi
    return 4 * (jac.conj() @ jac.T - np.outer(overlaps, overlaps.conj())).real
